apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-project-deploy
  labels:
    app: healthcare-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-project
  template:
    metadata:
      labels:
        app: healthcare-project
    spec:
      containers:
      - name: healthcare-project-container
        image: harishnhs/healthcare-project
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-project-np-service
  labels:
    app: healthcare-project
spec:
  selector:
    app: healthcare-project

  type: NodePort
  ports:
  - nodePort: 31034
    port: 8082
    targetPort: 8082
